
sonar.projectKey=SEU_USUARIO_OU_ORG_SystemDrawn-frontend
sonar.organization=SUA_ORGANIZACAO_NO_SONAR


sonar.sources=app,components,constants,hooks,providers,services,store


sonar.exclusions=node_modules/**,.expo/**,assets/**,**/*.spec.ts,**/*.test.ts


sonar.sourceEncoding=UTF-8 