
sonar.projectKey=SystemDrawn-frontend
sonar.projectName=SystemDrawn Frontend
sonar.projectVersion=1.0.0



sonar.sources=app,components,constants,hooks,providers,services,store


sonar.exclusions=**/node_modules/**,**/.expo/**,**/dist/**,**/build/**,**/assets/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,babel.config.js,metro.config.js,eslint.config.js


sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json

